apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rdpena.com
  namespace: cert-manager
spec:
  secretName: rdpena.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: 'rdpena.com'
  dnsNames:
  - "rdpena.com"