apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rdpena.com
  namespace: cert-manager
spec:
  secretName: testsecret-tls
  issuerRef:
    name: letsencryptletsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - "rdpena.com"
  - "frontend.rdpena.com"