apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme: 
    #server: https://acme-02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: rodoldo.depena@gmail.com
    privateKeySecretRef:
      name: testsecret-tls
    solvers:
    - http01:
        ingress:
          class: nginx  
